<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLXJ1xTz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLXJ1xTz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLXJ1xTz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLXJ1xTz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLXJ1xTz\App_KernelDevDebugContainer([
    'container.build_hash' => 'LXJ1xTz',
    'container.build_id' => 'd297e4d7',
    'container.build_time' => 1681379444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLXJ1xTz');
