<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCsx2Bmk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCsx2Bmk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCsx2Bmk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCsx2Bmk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCsx2Bmk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Csx2Bmk',
    'container.build_id' => '1c86db59',
    'container.build_time' => 1681377571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCsx2Bmk');
