<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUQDuz1Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUQDuz1Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUQDuz1Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUQDuz1Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUQDuz1Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'UQDuz1Z',
    'container.build_id' => '80501f71',
    'container.build_time' => 1681392503,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUQDuz1Z');
